### ISSUE TITLE
Best Practice for filtering text codec event data

### ISSUE THREAD

**Issue by kdHub** [GoogleCloudPlatform/gcsbeat#21]
Im looking to filter event data for unixtime, response codes, and client ips to be used in kibana. Is there a recommendation on best practice to achieve end goal of parsing event data from text codec or support for csv? If using logstash is there a example of what pipeline.conf should look like for below example as it seems I am not able to parse from event properly using csv, date, or grok plugins. Currently I am able to extract the timestamp using grok match => { "event" => "%{NUMBER:timestamp}" }

example storage log file in gcs:
```
"time_micros","c_ip","c_ip_type","c_ip_region","cs_method","cs_uri","sc_status"
"1519952401484239","192.168.1.1","1","","POST","path/file","200" 
"1519952400284508","192.168.1.1","1","","POST","path/file","200"
```
Example json event returned to elastic from beat
`{
  "_index": "logstash-2018.06.20",
  "_type": "doc",
  "_id": "XXXXXXXXXXXXXXXXXXX",
  "_version": 1,
  "_score": null,
  "_source": {
    "host": "vagrant",
    "@timestamp": "2018-06-20T21:29:44.722Z",
    "beat": {
      "version": "7.0.0-alpha1",
      "name": "vagrant",
      "hostname": "vagrant"
    },"event": "\"1528618411346382\",\"192.168.1.1\",\"1\",\"\",\"GET\",\"/path/file\",\"200\"",
"tags": [
      "beats_input_codec_plain_applied",
      "_dateparsefailure"
    ],
    "file": "XXXXXXXXXXXXXXXXXXXXXXX",
    "@version": "1",
    "message": "8813"
  },
  "fields": {
    "@timestamp": [
      "2018-06-20T21:29:44.722Z"
    ]
  },
  "sort": [
    1529530184722
  ]
}`

event labels for data to extract:
`"time_micros","c_ip","c_ip_type","c_ip_region","cs_method","cs_uri","sc_status"`

**Comment by kdHub** [comment]
I was able to get the main objective done with Grok filter in logstash pipeline but still open to feedback on best practices 
```

filter {
  grok {
    match => { "event" => '%{NUMBER:@timestamp}","%{IP:client}",(?<iptype>[^,]*),(?<ipregion>[^,]*),(?<method>[^,]*),"%{URIPATH:path}",(?<status>[^,]*),(?<bytes>[^,]*),"%{GREEDYDATA:misc}"' }
  }
}
```

**Comment by josephlewis42** [comment]
@kdHub if you're using Logstash, the grok processor is probably your best bet. There's also a [GCS Logstash input plugin I wrote](https://github.com/logstash-plugins/logstash-input-google_cloud_storage/pull/1) and is waiting a PR to become official. I have a published [rubygem](https://rubygems.org/gems/logstash-input-google_cloud_storage/versions/0.9.0-java) for it too.

If you don't want Logstash in your stack and are running a newer Elasticsearch, you could use an Elastic ingest pipeline with a [grok filter](https://www.elastic.co/guide/en/elasticsearch/reference/master/grok-processor.html) and ship the data straight from `gcsbeat` to your Elastic cluster.

Or, feel free to create a PR for a CSV codec. I'd be more than happy to help with it. Here's [the PR I made for the BLOB and CLOB codecs](https://github.com/GoogleCloudPlatform/gcsbeat/pull/18/files), there are only about four files you have to edit and you could base your CSV parser off of [`bufio.go`](https://github.com/GoogleCloudPlatform/gcsbeat/blob/master/beater/codec/bufio.go).

Does that help?

**Comment by kdHub** [comment]
Thanks for the detailed response. I will take these ideas and create PR if I'm able to get a csv workflow setup. For now grok seems to be doing the job and appreciate follow-up.

**Comment by kdHub** [comment]
The below worked well for csv auto generated from first line of log file. This is using gcsbeat as input to a logstash input filter. It's been stable for the most part and would recommend this method based on initial experience. Also second example uses the geoip plugin and date filters to override `@timestamp` from stripped unix timestamp that was provided in micro seconds and not supported yet based on my research... 

Example Logstash filters:
```
filter {
  csv {
        source => "event"
        separator => ","
        autodetect_column_names => true
        autogenerate_column_names => true
  }
}
  
output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => json }
}
```

```
filter {
  csv {
        source => "event"
        separator => ","
        autodetect_column_names => true
        autogenerate_column_names => true
  }
  mutate {
              gsub => ["time_micros","\d\d\d$",""]

  }
  geoip { 
    source => "client_ip_field" 
  }
  date {
    locale => "en"
    timezone => "UTC"
    match => ["time_micros","UNIX_MS", "ISO8601" ]
    target => "@timestamp"
  }
}
  
output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => json }
}
```
